### ISSUE TITLE
Advanced Feature Request - Master/Slave setup

### ISSUE THREAD

**Issue by sz7i** [JonasAlfredsson/docker-nginx-certbot#85] opened 2021-11-01 23:14 UTC
I'm looking for a solution that would allow to run more than one instance of docker-nginx-certbot behind a DNS load balancer.

Actually the problem and its potential solution are well described here https://stackoverflow.com/questions/42683935/using-certbot-lets-encrypt-with-dns-load-balancing.

The proposed solution can be implemented within this docker image by introducing a "Slave Setup" where the current implementation of this image can be called a "Master Setup"

The Slave differs from the Master in the following two aspects:

1. It doesn't run certbot at all, but runs just rsync to sync potentially changed certificates from the Master and triggers its local nginx to reload configs in case of changes

2. It redirects ACME challenge request not to localhost:81, but to Master:81 because once the Master is located behind a DNS load balancer, the load balancer may decide to send the ACME challenge request triggered by the Master to one of Slaves

Is this something realistically doable and interesting? Or do other alternatives already exist for this problem?

BTW, big thanks for maintaining this project!

**Comment by JonasAlfredsson** [comment] 2021-11-02 07:16
Interesting problem. I don't have any guides or similar to directly point you at, but it sounds like you are after the [acme-companion](https://github.com/nginx-proxy/acme-companion) where the Nginx container is decoupled from the container issuing the ACME requests. However, that setup requires you to mount the docker socket inside the Nginx container, and I think that is bonkers, which is part of the reason to why I decided to continue building on this project. 

I don't think there would be any issues for you to just overwrite the [certbot.conf](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src/nginx_conf.d/certbot.conf) in the slave to point at the master container, the problem is then how to propagate the certificates out to them and then notify them that they need to reload. 
You mention rsync, but that will add some complexity I don't think should be inside this container. Are the slave instances running on separate physical hosts, and if so do they all have access to some kind of network drive they can all read from?

**Comment by sz7i** [comment] 2021-11-02 10:49
Thanks for the prompt reply! I probably should have mentioned from the start that I actually have more objectives to achieve. I'd like to make the application running behind nginx instances not only load balanced, but also highly available and with reduced latencies. So I plan to locate nginx instances in different regions to get closer to users (advanced DNS servers can use geolocation to resolve names). The instances will be connected to each other directly via a global VPN.

I fully agree that using a common network drive will be much simpler than rsync, but would introduce a single point of failure and latencies. On the other side rsync solution is quite similar to certbot:

- it also has to run periodically
- it needs to know what certificates to synchronise
- it needs to trigger nginx reload once certificates change

Also temporary failures of rsync are not harmful like failures of certbot.

Do you think such a solution could be implemented in this docker or rather externally overwriting certbot.conf and scripts?

**Comment by JonasAlfredsson** [comment] 2021-11-05 08:00
Hmm, so you want run a globally distributed website where you want all of these instances to have their certificates rsynced to them from one central place.
This does not sound like something that this image should be responsible for. This image will automatically find the domain names in the config files and obtain them, but adding rsync and all the configuration of setting up secure connections from this container to the other ones sounds way out of scope for the "one task per container" philosophy. 

If you want to keep the functionality of this container, where it finds out the domain name by itself, I would probably look into adding a side car container (or look at running it directly on the host) which monitors the certificate files and push them to the remote instances. If you are using ssh/scp instead of rsync you could perhaps also send a SIGHUP to the remote Nginx containers for easy reload of them as well. That way we can keep those credentials and setup/restarting/debugging completely separate from this.

**Comment by sz7i** [comment] 2021-11-08 15:30
I agree it could be too much for this image and perhaps not that often needed. I'll try to implement one of the proposed solutions by myself. Thanks for your comments and hints!

**Closed** 2021-11-08 15:30 UTC

**Comment by JonasAlfredsson** [comment] 2021-11-09 07:16
Sounds good! If you want to discuss ideas or code solution don't hesitate to send me a message :)
